#ifndef GROUP0_H
#define GROUP0_H

#include "types.h"

// bubble
extern const GeoLayout bubble_geo[];
extern const GeoLayout purple_marble_geo[];
extern const Gfx bubble_seg4_dl_0401DD60[];
extern const Gfx bubble_seg4_dl_0401DDE0[];

// burn_smoke
extern const GeoLayout burn_smoke_geo[];
extern const Gfx burn_smoke_seg4_dl_04022000[];
extern const Gfx burn_smoke_seg4_dl_04022028[];
extern const Gfx burn_smoke_seg4_dl_04022048[];
extern const Gfx burn_smoke_seg4_dl_04022070[];

// sonic_trail
extern const GeoLayout sonic_trail_geo[];
extern const GeoLayout super_trail_geo[];
extern const Gfx sonic_trail_seg3_dl_0301B320[];
extern const Gfx sonic_trail_seg3_dl_0301B3B0[];
extern const Gfx sonic_trail_seg3_dl_0301B3C8[];
extern const Gfx sonic_trail_seg3_dl_0301B3E0[];
extern const Gfx sonic_trail_seg3_dl_0301B3F8[];
extern const Gfx sonic_trail_seg3_dl_0301B410[];
extern const Gfx sonic_trail_seg3_dl_0301B428[];
extern const Gfx sonic_trail_seg3_dl_0301B440[];
extern const Gfx sonic_trail_seg3_dl_0301B458[];
extern const Gfx sonic_trail_seg3_dl_0301B470[];
extern const Gfx sonic_trail_seg3_dl_0301B500[];
extern const Gfx sonic_trail_seg3_dl_0301B518[];
extern const Gfx sonic_trail_seg3_dl_0301B530[];
extern const Gfx sonic_trail_seg3_dl_0301B548[];
extern const Gfx sonic_trail_seg3_dl_0301B560[];
extern const Gfx sonic_trail_seg3_dl_0301B578[];
extern const Gfx sonic_trail_seg3_dl_0301B590[];
extern const Gfx sonic_trail_seg3_dl_0301B5A8[];







// mario
extern const GeoLayout mario_geo_face_and_wings[];
extern const GeoLayout mario_geo_left_hand[];
extern const GeoLayout mario_geo_right_hand[];
extern const GeoLayout mario_geo_body[];
extern const GeoLayout mario_geo_medium_poly_left_hand[];
extern const GeoLayout mario_geo_medium_poly_right_hand[];
extern const GeoLayout mario_geo_medium_poly_body[];
extern const GeoLayout mario_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_geo_low_poly_left_hand[];
extern const GeoLayout mario_geo_low_poly_right_hand[];
extern const GeoLayout mario_geo_low_poly_body[];
extern const GeoLayout mario_vanish_geo_face_and_wings[];
extern const GeoLayout mario_vanish_geo_left_hand[];
extern const GeoLayout mario_vanish_geo_right_hand[];
extern const GeoLayout mario_vanish_geo_body[];
extern const GeoLayout mario_vanish_geo_medium_poly_left_hand[];
extern const GeoLayout mario_vanish_geo_medium_poly_right_hand[];
extern const GeoLayout mario_vanish_geo_medium_poly_body[];
extern const GeoLayout mario_vanish_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_vanish_geo_low_poly_left_hand[];
extern const GeoLayout mario_vanish_geo_low_poly_right_hand[];
extern const GeoLayout mario_vanish_geo_low_poly_body[];
extern const GeoLayout mario_metal_geo_face_and_wings[];
extern const GeoLayout mario_metal_geo_left_hand[];
extern const GeoLayout mario_metal_geo_right_hand[];
extern const GeoLayout mario_metal_geo_body[];
extern const GeoLayout mario_metal_geo_medium_poly_left_hand[];
extern const GeoLayout mario_metal_geo_medium_poly_right_hand[];
extern const GeoLayout mario_metal_geo_medium_poly_body[];
extern const GeoLayout mario_metal_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_metal_geo_low_poly_left_hand[];
extern const GeoLayout mario_metal_geo_low_poly_right_hand[];
extern const GeoLayout mario_metal_geo_low_poly_body[];
extern const GeoLayout mario_metal_vanish_geo_face_and_wings[];
extern const GeoLayout mario_metal_vanish_geo_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_body[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_body[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_body[];
extern const GeoLayout mario_geo_load_body[];
extern const GeoLayout mario_geo_load_medium_poly_body[];
extern const GeoLayout mario_geo_load_low_poly_body[];
extern const GeoLayout mario_geo_render_body[];
extern const GeoLayout mario_geo[];
extern const Gfx mario_butt_dl[];
extern const Gfx mario_butt[];
extern const Gfx mario_metal_butt[];
extern const Gfx mario_left_arm_shared_dl[];
extern const Gfx mario_left_arm[];
extern const Gfx mario_left_forearm_shared_dl[];
extern const Gfx mario_left_hand_closed_shared_dl[];
extern const Gfx mario_left_hand_closed[];
extern const Gfx mario_right_arm_shared_dl[];
extern const Gfx mario_right_arm[];
extern const Gfx mario_right_forearm_shared_dl[];
extern const Gfx mario_right_hand_closed_dl[];
extern const Gfx mario_right_hand_closed[];
extern const Gfx mario_metal_right_hand_closed[];
extern const Gfx mario_left_thigh_dl[];
extern const Gfx mario_left_thigh[];
extern const Gfx mario_metal_left_thigh[];
extern const Gfx mario_left_leg_shared_dl[];
extern const Gfx mario_left_foot_shared_dl[];
extern const Gfx mario_left_foot[];
extern const Gfx mario_right_thigh_shared_dl[];
extern const Gfx mario_right_thigh[];
extern const Gfx mario_right_leg_shared_dl[];
extern const Gfx mario_right_foot_dl[];
extern const Gfx mario_right_foot[];
extern const Gfx mario_metal_right_foot[];
extern const Gfx mario_yellow_button_dl[];
extern const Gfx mario_pants_overalls_shared_dl[];
extern const Gfx mario_tshirt_shared_dl[];
extern const Gfx mario_torso_dl[];
extern const Gfx mario_torso[];
extern const Gfx mario_metal_torso_shared_dl[];
extern const Gfx mario_m_logo_dl[];
extern const Gfx mario_eyes_cap_on_dl[];
extern const Gfx mario_hair_sideburn_cap_on_dl[];
extern const Gfx mario_mustache_cap_on_dl[];
extern const Gfx mario_face_part_cap_on_dl[];
extern const Gfx mario_face_cap_dl[];
extern const Gfx mario_face_back_hair_cap_on_dl[];
extern const Gfx mario_face_cap_on_dl[];
extern const Gfx mario_cap_on_eyes_front[];
extern const Gfx mario_cap_on_eyes_half_closed[];
extern const Gfx mario_cap_on_eyes_closed[];
extern const Gfx mario_cap_on_eyes_right[];
extern const Gfx mario_cap_on_eyes_left[];
extern const Gfx mario_cap_on_eyes_up[];
extern const Gfx mario_cap_on_eyes_down[];
extern const Gfx mario_cap_on_eyes_dead[];
extern const Gfx mario_metal_cap_on_shared_dl[];
extern const Gfx mario_eyes_cap_off_dl[];
extern const Gfx mario_mustache_cap_off_dl[];
extern const Gfx mario_hair_sideburn_cap_off_dl[];
extern const Gfx mario_face_part_cap_off_dl[];
extern const Gfx mario_face_hair_cap_off_dl[];
extern const Gfx mario_face_cap_off_dl[];
extern const Gfx mario_cap_off_eyes_front[];
extern const Gfx mario_cap_off_eyes_half_closed[];
extern const Gfx mario_cap_off_eyes_closed[];
extern const Gfx mario_cap_off_eyes_right[];
extern const Gfx mario_cap_off_eyes_left[];
extern const Gfx mario_cap_off_eyes_up[];
extern const Gfx mario_cap_off_eyes_down[];
extern const Gfx mario_cap_off_eyes_dead[];
extern const Gfx mario_metal_cap_off_shared_dl[];
extern const Gfx mario_medium_poly_butt_dl[];
extern const Gfx mario_medium_poly_butt[];
extern const Gfx mario_metal_medium_poly_butt[];
extern const Gfx mario_medium_poly_left_arm_shared_dl[];
extern const Gfx mario_medium_poly_left_arm[];
extern const Gfx mario_medium_poly_left_forearm_shared_dl[];
extern const Gfx mario_medium_poly_left_hand_closed_shared_dl[];
extern const Gfx mario_medium_poly_left_hand_closed[];
extern const Gfx mario_medium_poly_right_arm_shared_dl[];
extern const Gfx mario_medium_poly_right_arm[];
extern const Gfx mario_medium_poly_right_forearm_shared_dl[];
extern const Gfx mario_medium_poly_right_hand_closed_dl[];
extern const Gfx mario_medium_poly_right_hand_closed[];
extern const Gfx mario_metal_medium_poly_right_hand_closed[];
extern const Gfx mario_medium_poly_left_thigh_dl[];
extern const Gfx mario_medium_poly_left_thigh[];
extern const Gfx mario_metal_medium_poly_left_thigh[];
extern const Gfx mario_medium_poly_left_leg_shared_dl[];
extern const Gfx mario_medium_poly_left_foot_shared_dl[];
extern const Gfx mario_medium_poly_left_foot[];
extern const Gfx mario_medium_poly_right_thigh_shared_dl[];
extern const Gfx mario_medium_poly_right_thigh[];
extern const Gfx mario_medium_poly_right_leg_shared_dl[];
extern const Gfx mario_medium_poly_right_foot_dl[];
extern const Gfx mario_medium_poly_right_foot[];
extern const Gfx mario_metal_medium_poly_right_foot[];
extern const Gfx mario_medium_poly_yellow_button_dl[];
extern const Gfx mario_medium_poly_pants_overalls_shared_dl[];
extern const Gfx mario_medium_poly_tshirt_shared_dl[];
extern const Gfx mario_medium_poly_torso_dl[];
extern const Gfx mario_medium_poly_torso[];
extern const Gfx mario_metal_medium_poly_torso[];
extern const Gfx mario_low_poly_butt_dl[];
extern const Gfx mario_low_poly_butt[];
extern const Gfx mario_metal_low_poly_butt[];
extern const Gfx mario_low_poly_left_arm_shared_dl[];
extern const Gfx mario_low_poly_left_arm[];
extern const Gfx mario_low_poly_left_forearm_shared_dl[];
extern const Gfx mario_low_poly_left_hand_closed_shared_dl[];
extern const Gfx mario_low_poly_left_hand_closed[];
extern const Gfx mario_low_poly_right_arm_shared_dl[];
extern const Gfx mario_low_poly_right_arm[];
extern const Gfx mario_low_poly_right_forearm_shared_dl[];
extern const Gfx mario_low_poly_right_hand_closed_dl[];
extern const Gfx mario_low_poly_right_hand_closed[];
extern const Gfx mario_metal_low_poly_right_hand_closed[];
extern const Gfx mario_low_poly_left_thigh_dl[];
extern const Gfx mario_low_poly_left_thigh[];
extern const Gfx mario_metal_low_poly_left_thigh[];
extern const Gfx mario_low_poly_left_leg_shared_dl[];
extern const Gfx mario_low_poly_left_foot_shared_dl[];
extern const Gfx mario_low_poly_left_foot[];
extern const Gfx mario_low_poly_right_thigh_shared_dl[];
extern const Gfx mario_low_poly_right_thigh[];
extern const Gfx mario_low_poly_right_leg_shared_dl[];
extern const Gfx mario_low_poly_right_foot_dl[];
extern const Gfx mario_low_poly_right_foot[];
extern const Gfx mario_metal_low_poly_right_foot[];
extern const Gfx mario_low_poly_yellow_button_dl[];
extern const Gfx mario_low_poly_pants_overalls_shared_dl[];
extern const Gfx mario_low_poly_tshirt_shared_dl[];
extern const Gfx mario_low_poly_torso_dl[];
extern const Gfx mario_low_poly_torso[];
extern const Gfx mario_metal_low_poly_torso[];
extern const Gfx mario_low_poly_mario_m_logo_dl[];
extern const Gfx mario_low_poly_eyes_cap_on_dl[];
extern const Gfx mario_low_poly_mustache_cap_on_dl[];
extern const Gfx mario_low_poly_face_part_cap_on_dl[];
extern const Gfx mario_low_poly_face_cap_dl[];
extern const Gfx mario_low_poly_face_back_hair_cap_on_dl[];
extern const Gfx mario_low_poly_face_cap_on_dl[];
extern const Gfx mario_low_poly_cap_on_eyes_front[];
extern const Gfx mario_low_poly_cap_on_eyes_half_closed[];
extern const Gfx mario_low_poly_cap_on_eyes_closed[];
extern const Gfx mario_low_poly_cap_on_eyes_right[];
extern const Gfx mario_low_poly_cap_on_eyes_left[];
extern const Gfx mario_low_poly_cap_on_eyes_up[];
extern const Gfx mario_low_poly_cap_on_eyes_down[];
extern const Gfx mario_low_poly_cap_on_eyes_dead[];
extern const Gfx mario_metal_low_poly_cap_on[];
extern const Gfx mario_low_poly_mario_eyes_cap_off_dl[];
extern const Gfx mario_low_poly_mustache_cap_off_dl[];
extern const Gfx mario_low_poly_face_part_cap_off_dl[];
extern const Gfx mario_low_poly_face_hair_cap_off_dl[];
extern const Gfx mario_low_poly_face_cap_off_dl[];
extern const Gfx mario_low_poly_cap_off_eyes_front[];
extern const Gfx mario_low_poly_cap_off_eyes_half_closed[];
extern const Gfx mario_low_poly_cap_off_eyes_closed[];
extern const Gfx mario_low_poly_cap_off_eyes_right[];
extern const Gfx mario_low_poly_cap_off_eyes_left[];
extern const Gfx mario_low_poly_cap_off_eyes_up[];
extern const Gfx mario_low_poly_cap_off_eyes_down[];
extern const Gfx mario_low_poly_cap_off_eyes_dead[];
extern const Gfx mario_metal_low_poly_cap_off[];
extern const Gfx mario_left_hand_open_shared_dl[];
extern const Gfx mario_left_hand_open[];
extern const Gfx mario_right_hand_open_dl[];
extern const Gfx mario_right_hand_open[];
extern const Gfx mario_metal_right_hand_open[];
extern const Gfx mario_right_hand_cap_m_logo_dl[];
extern const Gfx mario_right_hand_cap_top_dl[];
extern const Gfx mario_right_hand_cap_hand_position_dl[];
extern const Gfx mario_right_hand_cap_bottom_dl[];
extern const Gfx mario_right_hand_cap_dl[];
extern const Gfx mario_right_hand_cap_wings_half_1_dl[];
extern const Gfx mario_right_hand_cap_wings_half_2_dl[];
extern const Gfx mario_right_hand_cap_wings_intial_dl[];
extern const Gfx mario_right_hand_cap_wings_end_dl[];
extern const Gfx mario_right_hand_cap[];
extern const Gfx mario_right_hand_cap_wings[];
extern const Gfx mario_metal_right_hand_cap_shared_dl[];
extern const Gfx mario_metal_right_hand_cap_shared_dl_wings[];
extern const Gfx mario_right_hand_peace_shared_dl[];
extern const Gfx mario_right_hand_peace[];
extern const Gfx mario_cap_unused_m_logo_dl[];
extern const Gfx mario_cap_unused_base_top_dl[];
extern const Gfx mario_cap_unused_base_bottom_dl[];
extern const Gfx mario_cap_unused_base_dl[];
extern const Gfx mario_wings_half_1_unused_dl[];
extern const Gfx mario_wings_half_2_unused_dl[];
extern const Gfx mario_cap_wings_unused_intial_dl[];
extern const Gfx mario_cap_wings_unused_end_dl[];
extern const Gfx mario_cap_unused_dl[];
extern const Gfx mario_metal_cap_unused_dl[];
extern const Gfx mario_cap_wings_unused[];
extern const Gfx mario_metal_cap_wings_unused[];
extern const Gfx mario_wings_half_1_dl[];
extern const Gfx mario_wings_half_2_dl[];
extern const Gfx mario_cap_wings[];
extern const Gfx mario_cap_wings_transparent[];
extern const Gfx mario_metal_cap_wings[];
extern const Gfx mario_metal_cap_wings_transparent[];

// sparkle
extern const GeoLayout sparkles_geo[];
extern const Gfx sparkles_seg4_dl_0402A490[];
extern const Gfx sparkles_seg4_dl_0402A4F8[];
extern const Gfx sparkles_seg4_dl_0402A510[];
extern const Gfx sparkles_seg4_dl_0402A528[];
extern const Gfx sparkles_seg4_dl_0402A540[];
extern const Gfx sparkles_seg4_dl_0402A558[];
extern const Gfx sparkles_seg4_dl_0402A570[];

// sparkle_animation
extern const GeoLayout sparkles_animation_geo[];
extern const Gfx sparkles_animation_seg4_dl_04035288[];
extern const Gfx sparkles_animation_seg4_dl_04035300[];
extern const Gfx sparkles_animation_seg4_dl_04035318[];
extern const Gfx sparkles_animation_seg4_dl_04035330[];
extern const Gfx sparkles_animation_seg4_dl_04035348[];
extern const Gfx sparkles_animation_seg4_dl_04035360[];

// stomp_smoke
extern const GeoLayout small_water_splash_geo[];
extern const GeoLayout mario_TODO_geo_0000E0[];
extern const Gfx stomp_smoke_seg4_dl_04025148[];
extern const Gfx stomp_smoke_seg4_dl_04025190[];
extern const Gfx stomp_smoke_seg4_dl_040251C8[];
extern const Gfx stomp_smoke_seg4_dl_040251E0[];
extern const Gfx stomp_smoke_seg4_dl_040251F8[];
extern const Gfx stomp_smoke_seg4_dl_04025210[];
extern const Gfx stomp_smoke_seg4_dl_04025228[];
extern const Gfx stomp_smoke_seg4_dl_04025240[];
extern const Gfx stomp_smoke_seg4_dl_04025258[];
extern const Gfx stomp_smoke_seg4_dl_04025270[];
extern const Gfx stomp_smoke_seg4_dl_04025288[];
extern const Gfx stomp_smoke_seg4_dl_040252A0[];
extern const Gfx stomp_smoke_seg4_dl_040252B8[];
extern const Gfx stomp_smoke_seg4_dl_040252D0[];
extern const Gfx stomp_smoke_seg4_dl_040252E8[];
extern const Gfx stomp_smoke_seg4_dl_04025300[];

// walk_smoke
extern const GeoLayout smoke_geo[];
extern const Gfx smoke_seg4_dl_040216A0[];
extern const Gfx smoke_seg4_dl_04021718[];
extern const Gfx smoke_seg4_dl_04021730[];
extern const Gfx smoke_seg4_dl_04021748[];
extern const Gfx smoke_seg4_dl_04021760[];
extern const Gfx smoke_seg4_dl_04021778[];
extern const Gfx smoke_seg4_dl_04021790[];
extern const Gfx smoke_seg4_dl_040217A8[];

// water_splash
extern const GeoLayout water_splash_geo[];
extern const Gfx water_splash_seg4_dl_040325C8[];
extern const Gfx water_splash_seg4_dl_04032640[];
extern const Gfx water_splash_seg4_dl_04032658[];
extern const Gfx water_splash_seg4_dl_04032670[];
extern const Gfx water_splash_seg4_dl_04032688[];
extern const Gfx water_splash_seg4_dl_040326A0[];
extern const Gfx water_splash_seg4_dl_040326B8[];
extern const Gfx water_splash_seg4_dl_040326D0[];
extern const Gfx water_splash_seg4_dl_040326E8[];

// water_waves
extern const GeoLayout idle_water_wave_geo[];
extern const GeoLayout wave_trail_geo[];
extern const Gfx water_wave_seg4_dl_04027358[];
extern const Gfx water_wave_seg4_dl_040273A0[];
extern const Gfx water_wave_seg4_dl_040273D8[];
extern const Gfx water_wave_seg4_dl_040273F0[];
extern const Gfx water_wave_seg4_dl_04027408[];
extern const Gfx water_wave_seg4_dl_04027420[];
extern const Gfx water_wave_seg4_dl_04027438[];

// white_particle_small
extern const Gfx white_particle_small_dl_begin[];
extern const Gfx white_particle_small_dl_end[];
extern const Gfx white_particle_small_dl[];
extern const Gfx white_particle_small_unused_dl[];


// sonic_ball
extern const GeoLayout sonic_ball_geo[];
extern const Gfx sonic_ball_seg5_dl_05010D30[];
extern const Gfx sonic_ball_seg5_dl_05011000[];

// sonic_ball
extern const GeoLayout super_ball_geo[];
extern const Gfx super_ball_seg5_dl_05010D30[];
extern const Gfx super_ball_seg5_dl_05011000[];

// super_sonic
extern const GeoLayout super_sonic_geo[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7[];
extern const GeoLayout super_sonic_armature_002_switch_option_001[];
extern const GeoLayout super_sonic_right_hand_open_armature[];
extern const GeoLayout super_sonic_left_hand_open_armature[];
extern const GeoLayout super_sonic_left_hand_peace_armature[];
extern const GeoLayout super_sonic_left_hand_cap_armature[];
extern const GeoLayout super_sonic_left_hand_wing_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_armature_002_switch_option_001[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_right_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_left_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_left_hand_peace_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_left_hand_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_left_hand_wing_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_armature_002_switch_option_001[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_right_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_left_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_left_hand_peace_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_left_hand_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_left_hand_wing_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_armature_002_switch_option_001[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_right_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_left_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_left_hand_peace_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_left_hand_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_left_hand_wing_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[];
extern const GeoLayout super_sonic_geo[];
extern Vtx super_sonic_000_offset_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_mesh_tri_0[];
extern Vtx super_sonic_000_offset_mesh_vtx_1[24];
extern Gfx super_sonic_000_offset_mesh_tri_1[];
extern Vtx super_sonic_000_offset_001_mesh_vtx_0[16];
extern Gfx super_sonic_000_offset_001_mesh_tri_0[];
extern Vtx super_sonic_000_offset_001_mesh_vtx_1[8];
extern Gfx super_sonic_000_offset_001_mesh_tri_1[];
extern Vtx super_sonic_000_offset_001_mesh_vtx_2[100];
extern Gfx super_sonic_000_offset_001_mesh_tri_2[];
extern Vtx super_sonic_000_offset_001_mesh_vtx_3[16];
extern Gfx super_sonic_000_offset_001_mesh_tri_3[];
extern Vtx super_sonic_000_offset_001_skinned_vtx_0[11];
extern Gfx super_sonic_000_offset_001_skinned_tri_0[];
extern Vtx super_sonic_000_offset_001_skinned_vtx_1[3];
extern Gfx super_sonic_000_offset_001_skinned_tri_1[];
extern Vtx super_sonic_000_displaylist_mesh_vtx_0[13];
extern Gfx super_sonic_000_displaylist_mesh_tri_0[];
extern Vtx super_sonic_000_displaylist_mesh_vtx_1[115];
extern Gfx super_sonic_000_displaylist_mesh_tri_1[];
extern Vtx super_sonic_000_displaylist_mesh_vtx_2[63];
extern Gfx super_sonic_000_displaylist_mesh_tri_2[];
extern Vtx super_sonic_000_displaylist_mesh_vtx_3[559];
extern Gfx super_sonic_000_displaylist_mesh_tri_3[];
extern Vtx super_sonic_002_switch_option_head__no_cap__mesh_vtx_0[103];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_tri_0[];
extern Vtx super_sonic_002_switch_option_head__no_cap__mesh_vtx_1[30];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_tri_1[];
extern Vtx super_sonic_002_switch_option_head__no_cap__mesh_vtx_2[12];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_tri_2[];
extern Vtx super_sonic_002_switch_option_head__no_cap__mesh_vtx_3[92];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_tri_3[];
extern Vtx super_sonic_000_displaylist_001_mesh_vtx_0[4];
extern Gfx super_sonic_000_displaylist_001_mesh_tri_0[];
extern Vtx super_sonic_000_displaylist_001_mesh_vtx_1[4];
extern Gfx super_sonic_000_displaylist_001_mesh_tri_1[];
extern Vtx super_sonic_000_displaylist_002_mesh_vtx_0[4];
extern Gfx super_sonic_000_displaylist_002_mesh_tri_0[];
extern Vtx super_sonic_000_displaylist_002_mesh_vtx_1[4];
extern Gfx super_sonic_000_displaylist_002_mesh_tri_1[];
extern Vtx super_sonic_000_offset_003_mesh_vtx_0[31];
extern Gfx super_sonic_000_offset_003_mesh_tri_0[];
extern Vtx super_sonic_000_offset_004_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_004_mesh_tri_0[];
extern Vtx super_sonic_000_offset_004_mesh_vtx_1[12];
extern Gfx super_sonic_000_offset_004_mesh_tri_1[];
extern Vtx super_sonic_000_offset_004_skinned_vtx_0[6];
extern Gfx super_sonic_000_offset_004_skinned_tri_0[];
extern Vtx super_sonic_000_displaylist_003_mesh_vtx_0[46];
extern Gfx super_sonic_000_displaylist_003_mesh_tri_0[];
extern Vtx super_sonic_002_switch_option_right_hand_open_mesh_vtx_0[58];
extern Gfx super_sonic_002_switch_option_right_hand_open_mesh_tri_0[];
extern Vtx super_sonic_000_offset_006_mesh_vtx_0[40];
extern Gfx super_sonic_000_offset_006_mesh_tri_0[];
extern Vtx super_sonic_000_offset_007_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_007_mesh_tri_0[];
extern Vtx super_sonic_000_offset_007_mesh_vtx_1[12];
extern Gfx super_sonic_000_offset_007_mesh_tri_1[];
extern Vtx super_sonic_000_offset_007_skinned_vtx_0[6];
extern Gfx super_sonic_000_offset_007_skinned_tri_0[];
extern Vtx super_sonic_000_displaylist_004_mesh_vtx_0[36];
extern Gfx super_sonic_000_displaylist_004_mesh_tri_0[];
extern Vtx super_sonic_002_switch_option_left_hand_open_mesh_vtx_0[57];
extern Gfx super_sonic_002_switch_option_left_hand_open_mesh_tri_0[];
extern Vtx super_sonic_004_switch_option_left_hand_peace_mesh_vtx_0[73];
extern Gfx super_sonic_004_switch_option_left_hand_peace_mesh_tri_0[];
extern Vtx super_sonic_005_switch_option_left_hand_cap_mesh_vtx_0[59];
extern Gfx super_sonic_005_switch_option_left_hand_cap_mesh_tri_0[];
extern Vtx super_sonic_005_switch_option_left_hand_cap_mesh_vtx_1[36];
extern Gfx super_sonic_005_switch_option_left_hand_cap_mesh_tri_1[];
extern Vtx super_sonic_006_switch_option_left_hand_wing_cap_mesh_vtx_0[59];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_mesh_tri_0[];
extern Vtx super_sonic_006_switch_option_left_hand_wing_cap_mesh_vtx_1[36];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_mesh_tri_1[];
extern Vtx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_vtx_0[8];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_tri_0[];
extern Vtx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_vtx_1[8];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_tri_1[];
extern Vtx super_sonic_000_offset_009_mesh_vtx_0[8];
extern Gfx super_sonic_000_offset_009_mesh_tri_0[];
extern Vtx super_sonic_000_offset_009_mesh_vtx_1[13];
extern Gfx super_sonic_000_offset_009_mesh_tri_1[];
extern Vtx super_sonic_000_offset_009_skinned_vtx_0[11];
extern Gfx super_sonic_000_offset_009_skinned_tri_0[];
extern Vtx super_sonic_000_offset_010_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_010_mesh_tri_0[];
extern Vtx super_sonic_000_offset_010_mesh_vtx_1[27];
extern Gfx super_sonic_000_offset_010_mesh_tri_1[];
extern Vtx super_sonic_000_offset_010_mesh_vtx_2[41];
extern Gfx super_sonic_000_offset_010_mesh_tri_2[];
extern Vtx super_sonic_000_offset_010_mesh_vtx_3[8];
extern Gfx super_sonic_000_offset_010_mesh_tri_3[];
extern Vtx super_sonic_000_offset_010_skinned_vtx_0[6];
extern Gfx super_sonic_000_offset_010_skinned_tri_0[];
extern Vtx super_sonic_000_offset_011_mesh_vtx_0[123];
extern Gfx super_sonic_000_offset_011_mesh_tri_0[];
extern Vtx super_sonic_000_offset_011_mesh_vtx_1[12];
extern Gfx super_sonic_000_offset_011_mesh_tri_1[];
extern Vtx super_sonic_000_offset_012_mesh_vtx_0[8];
extern Gfx super_sonic_000_offset_012_mesh_tri_0[];
extern Vtx super_sonic_000_offset_012_mesh_vtx_1[13];
extern Gfx super_sonic_000_offset_012_mesh_tri_1[];
extern Vtx super_sonic_000_offset_012_skinned_vtx_0[11];
extern Gfx super_sonic_000_offset_012_skinned_tri_0[];
extern Vtx super_sonic_000_offset_013_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_013_mesh_tri_0[];
extern Vtx super_sonic_000_offset_013_mesh_vtx_1[27];
extern Gfx super_sonic_000_offset_013_mesh_tri_1[];
extern Vtx super_sonic_000_offset_013_mesh_vtx_2[41];
extern Gfx super_sonic_000_offset_013_mesh_tri_2[];
extern Vtx super_sonic_000_offset_013_mesh_vtx_3[8];
extern Gfx super_sonic_000_offset_013_mesh_tri_3[];
extern Vtx super_sonic_000_offset_013_skinned_vtx_0[6];
extern Gfx super_sonic_000_offset_013_skinned_tri_0[];
extern Vtx super_sonic_000_displaylist_005_mesh_vtx_0[128];
extern Gfx super_sonic_000_displaylist_005_mesh_tri_0[];
extern Vtx super_sonic_000_displaylist_005_mesh_vtx_1[12];
extern Gfx super_sonic_000_displaylist_005_mesh_tri_1[];

extern Gfx super_sonic_000_offset_mesh[];
extern Gfx super_sonic_000_offset_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_001_mesh[];
extern Gfx super_sonic_000_offset_001_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_001_skinned[];
extern Gfx super_sonic_000_offset_001_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_mesh[];
extern Gfx super_sonic_000_displaylist_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_mesh_mat_override_face_0___eye_open_1[];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh[];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_mat_override_face_0___eye_open_1[];
extern Gfx super_sonic_000_displaylist_001_mesh[];
extern Gfx super_sonic_000_displaylist_001_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_002_mesh[];
extern Gfx super_sonic_000_displaylist_002_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_003_mesh[];
extern Gfx super_sonic_000_offset_003_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_004_mesh[];
extern Gfx super_sonic_000_offset_004_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_004_skinned[];
extern Gfx super_sonic_000_offset_004_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_003_mesh[];
extern Gfx super_sonic_000_displaylist_003_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_002_switch_option_right_hand_open_mesh[];
extern Gfx super_sonic_002_switch_option_right_hand_open_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_006_mesh[];
extern Gfx super_sonic_000_offset_006_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_007_mesh[];
extern Gfx super_sonic_000_offset_007_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_007_skinned[];
extern Gfx super_sonic_000_offset_007_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_004_mesh[];
extern Gfx super_sonic_000_displaylist_004_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_002_switch_option_left_hand_open_mesh[];
extern Gfx super_sonic_002_switch_option_left_hand_open_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_004_switch_option_left_hand_peace_mesh[];
extern Gfx super_sonic_004_switch_option_left_hand_peace_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_005_switch_option_left_hand_cap_mesh[];
extern Gfx super_sonic_005_switch_option_left_hand_cap_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_mesh[];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh[];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_009_mesh[];
extern Gfx super_sonic_000_offset_009_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_009_skinned[];
extern Gfx super_sonic_000_offset_009_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_010_mesh[];
extern Gfx super_sonic_000_offset_010_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_010_skinned[];
extern Gfx super_sonic_000_offset_010_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_011_mesh[];
extern Gfx super_sonic_000_offset_011_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_012_mesh[];
extern Gfx super_sonic_000_offset_012_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_012_skinned[];
extern Gfx super_sonic_000_offset_012_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_013_mesh[];
extern Gfx super_sonic_000_offset_013_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_013_skinned[];
extern Gfx super_sonic_000_offset_013_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_005_mesh[];
extern Gfx super_sonic_000_displaylist_005_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_material_revert_render_settings[];

extern const GeoLayout sonic_ball_001_switch_opt1[];
extern const GeoLayout sonic_ball_001_switch_opt2[];
extern const GeoLayout sonic_ball_001_switch_opt3[];
extern const GeoLayout geo[];
extern Vtx sonic_ball_000_offset_mesh_vtx_0[80];
extern Gfx sonic_ball_000_offset_mesh_tri_0[];

extern Gfx sonic_ball_000_offset_mesh[];
extern Gfx sonic_ball_000_offset_mesh_mat_override_metal_0[];
extern Gfx sonic_ball_material_revert_render_settings[];


extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7[];
extern const GeoLayout mario_armature_002_switch_option_002[];
extern const GeoLayout mario_right_hand_open_armature[];
extern const GeoLayout mario_left_hand_open_armature[];
extern const GeoLayout mario_left_hand_peace_armature[];
extern const GeoLayout mario_left_hand_cap_armature[];
extern const GeoLayout mario_left_hand_wing_cap_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_armature_002_switch_option_002[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_right_hand_open_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_left_hand_open_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_left_hand_peace_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_left_hand_cap_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_left_hand_wing_cap_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt1[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_armature_002_switch_option_002[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_right_hand_open_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_left_hand_open_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_left_hand_peace_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_left_hand_cap_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_left_hand_wing_cap_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt2[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_armature_002_switch_option_002[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_right_hand_open_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_left_hand_open_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_left_hand_peace_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_left_hand_cap_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_left_hand_wing_cap_armature[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt3[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[];
extern const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[];
extern const GeoLayout mario_geo[];
extern Vtx mario_000_offset_mesh_vtx_0[6];
extern Gfx mario_000_offset_mesh_tri_0[];
extern Vtx mario_000_offset_mesh_vtx_1[24];
extern Gfx mario_000_offset_mesh_tri_1[];
extern Vtx mario_000_offset_001_mesh_vtx_0[16];
extern Gfx mario_000_offset_001_mesh_tri_0[];
extern Vtx mario_000_offset_001_mesh_vtx_1[8];
extern Gfx mario_000_offset_001_mesh_tri_1[];
extern Vtx mario_000_offset_001_mesh_vtx_2[100];
extern Gfx mario_000_offset_001_mesh_tri_2[];
extern Vtx mario_000_offset_001_mesh_vtx_3[16];
extern Gfx mario_000_offset_001_mesh_tri_3[];
extern Vtx mario_000_offset_001_skinned_vtx_0[11];
extern Gfx mario_000_offset_001_skinned_tri_0[];
extern Vtx mario_000_offset_001_skinned_vtx_1[3];
extern Gfx mario_000_offset_001_skinned_tri_1[];
extern Vtx mario_000_displaylist_mesh_vtx_0[453];
extern Gfx mario_000_displaylist_mesh_tri_0[];
extern Vtx mario_000_displaylist_mesh_vtx_1[85];
extern Gfx mario_000_displaylist_mesh_tri_1[];
extern Vtx mario_000_displaylist_mesh_vtx_2[42];
extern Gfx mario_000_displaylist_mesh_tri_2[];
extern Vtx mario_000_displaylist_mesh_vtx_3[26];
extern Gfx mario_000_displaylist_mesh_tri_3[];
extern Vtx mario_000_displaylist_mesh_vtx_4[13];
extern Gfx mario_000_displaylist_mesh_tri_4[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_vtx_0[103];
extern Gfx mario_002_switch_option_head__no_cap__mesh_tri_0[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_vtx_1[30];
extern Gfx mario_002_switch_option_head__no_cap__mesh_tri_1[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_vtx_2[12];
extern Gfx mario_002_switch_option_head__no_cap__mesh_tri_2[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_vtx_3[92];
extern Gfx mario_002_switch_option_head__no_cap__mesh_tri_3[];
extern Vtx mario_000_displaylist_001_mesh_vtx_0[4];
extern Gfx mario_000_displaylist_001_mesh_tri_0[];
extern Vtx mario_000_displaylist_001_mesh_vtx_1[4];
extern Gfx mario_000_displaylist_001_mesh_tri_1[];
extern Vtx mario_000_displaylist_002_mesh_vtx_0[4];
extern Gfx mario_000_displaylist_002_mesh_tri_0[];
extern Vtx mario_000_displaylist_002_mesh_vtx_1[4];
extern Gfx mario_000_displaylist_002_mesh_tri_1[];
extern Vtx mario_000_offset_003_mesh_vtx_0[31];
extern Gfx mario_000_offset_003_mesh_tri_0[];
extern Vtx mario_000_offset_004_mesh_vtx_0[6];
extern Gfx mario_000_offset_004_mesh_tri_0[];
extern Vtx mario_000_offset_004_mesh_vtx_1[12];
extern Gfx mario_000_offset_004_mesh_tri_1[];
extern Vtx mario_000_offset_004_skinned_vtx_0[6];
extern Gfx mario_000_offset_004_skinned_tri_0[];
extern Vtx mario_000_displaylist_003_mesh_vtx_0[46];
extern Gfx mario_000_displaylist_003_mesh_tri_0[];
extern Vtx mario_002_switch_option_right_hand_open_mesh_vtx_0[58];
extern Gfx mario_002_switch_option_right_hand_open_mesh_tri_0[];
extern Vtx mario_000_offset_006_mesh_vtx_0[40];
extern Gfx mario_000_offset_006_mesh_tri_0[];
extern Vtx mario_000_offset_007_mesh_vtx_0[6];
extern Gfx mario_000_offset_007_mesh_tri_0[];
extern Vtx mario_000_offset_007_mesh_vtx_1[12];
extern Gfx mario_000_offset_007_mesh_tri_1[];
extern Vtx mario_000_offset_007_skinned_vtx_0[6];
extern Gfx mario_000_offset_007_skinned_tri_0[];
extern Vtx mario_000_displaylist_004_mesh_vtx_0[36];
extern Gfx mario_000_displaylist_004_mesh_tri_0[];
extern Vtx mario_002_switch_option_left_hand_open_mesh_vtx_0[57];
extern Gfx mario_002_switch_option_left_hand_open_mesh_tri_0[];
extern Vtx mario_004_switch_option_left_hand_peace_mesh_vtx_0[73];
extern Gfx mario_004_switch_option_left_hand_peace_mesh_tri_0[];
extern Vtx mario_005_switch_option_left_hand_cap_mesh_vtx_0[59];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_tri_0[];
extern Vtx mario_005_switch_option_left_hand_cap_mesh_vtx_1[36];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_tri_1[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_mesh_vtx_0[59];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_tri_0[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_mesh_vtx_1[36];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_tri_1[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_wings_mesh_vtx_0[8];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_tri_0[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_wings_mesh_vtx_1[8];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_tri_1[];
extern Vtx mario_000_offset_009_mesh_vtx_0[8];
extern Gfx mario_000_offset_009_mesh_tri_0[];
extern Vtx mario_000_offset_009_mesh_vtx_1[13];
extern Gfx mario_000_offset_009_mesh_tri_1[];
extern Vtx mario_000_offset_009_skinned_vtx_0[11];
extern Gfx mario_000_offset_009_skinned_tri_0[];
extern Vtx mario_000_offset_010_mesh_vtx_0[6];
extern Gfx mario_000_offset_010_mesh_tri_0[];
extern Vtx mario_000_offset_010_mesh_vtx_1[9];
extern Gfx mario_000_offset_010_mesh_tri_1[];
extern Vtx mario_000_offset_010_mesh_vtx_2[41];
extern Gfx mario_000_offset_010_mesh_tri_2[];
extern Vtx mario_000_offset_010_mesh_vtx_3[16];
extern Gfx mario_000_offset_010_mesh_tri_3[];
extern Vtx mario_000_offset_010_skinned_vtx_0[6];
extern Gfx mario_000_offset_010_skinned_tri_0[];
extern Vtx mario_000_offset_011_mesh_vtx_0[58];
extern Gfx mario_000_offset_011_mesh_tri_0[];
extern Vtx mario_000_offset_011_mesh_vtx_1[16];
extern Gfx mario_000_offset_011_mesh_tri_1[];
extern Vtx mario_000_offset_011_mesh_vtx_2[46];
extern Gfx mario_000_offset_011_mesh_tri_2[];
extern Vtx mario_000_offset_011_mesh_vtx_3[12];
extern Gfx mario_000_offset_011_mesh_tri_3[];
extern Vtx mario_000_offset_012_mesh_vtx_0[8];
extern Gfx mario_000_offset_012_mesh_tri_0[];
extern Vtx mario_000_offset_012_mesh_vtx_1[13];
extern Gfx mario_000_offset_012_mesh_tri_1[];
extern Vtx mario_000_offset_012_skinned_vtx_0[11];
extern Gfx mario_000_offset_012_skinned_tri_0[];
extern Vtx mario_000_offset_013_mesh_vtx_0[6];
extern Gfx mario_000_offset_013_mesh_tri_0[];
extern Vtx mario_000_offset_013_mesh_vtx_1[9];
extern Gfx mario_000_offset_013_mesh_tri_1[];
extern Vtx mario_000_offset_013_mesh_vtx_2[41];
extern Gfx mario_000_offset_013_mesh_tri_2[];
extern Vtx mario_000_offset_013_mesh_vtx_3[16];
extern Gfx mario_000_offset_013_mesh_tri_3[];
extern Vtx mario_000_offset_013_skinned_vtx_0[6];
extern Gfx mario_000_offset_013_skinned_tri_0[];
extern Vtx mario_000_displaylist_005_mesh_vtx_0[55];
extern Gfx mario_000_displaylist_005_mesh_tri_0[];
extern Vtx mario_000_displaylist_005_mesh_vtx_1[46];
extern Gfx mario_000_displaylist_005_mesh_tri_1[];
extern Vtx mario_000_displaylist_005_mesh_vtx_2[12];
extern Gfx mario_000_displaylist_005_mesh_tri_2[];
extern Vtx mario_000_displaylist_005_mesh_vtx_3[16];
extern Gfx mario_000_displaylist_005_mesh_tri_3[];

extern Gfx mario_000_offset_mesh[];
extern Gfx mario_000_offset_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_001_mesh[];
extern Gfx mario_000_offset_001_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_001_skinned[];
extern Gfx mario_000_offset_001_skinned_mat_override_metal_003_0[];
extern Gfx mario_000_displaylist_mesh[];
extern Gfx mario_000_displaylist_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_displaylist_mesh_mat_override_face_0___eye_open_1[];
extern Gfx mario_002_switch_option_head__no_cap__mesh[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_mat_override_metal_003_0[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_mat_override_face_0___eye_open_1[];
extern Gfx mario_000_displaylist_001_mesh[];
extern Gfx mario_000_displaylist_001_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_displaylist_002_mesh[];
extern Gfx mario_000_displaylist_002_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_003_mesh[];
extern Gfx mario_000_offset_003_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_004_mesh[];
extern Gfx mario_000_offset_004_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_004_skinned[];
extern Gfx mario_000_offset_004_skinned_mat_override_metal_003_0[];
extern Gfx mario_000_displaylist_003_mesh[];
extern Gfx mario_000_displaylist_003_mesh_mat_override_metal_003_0[];
extern Gfx mario_002_switch_option_right_hand_open_mesh[];
extern Gfx mario_002_switch_option_right_hand_open_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_006_mesh[];
extern Gfx mario_000_offset_006_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_007_mesh[];
extern Gfx mario_000_offset_007_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_007_skinned[];
extern Gfx mario_000_offset_007_skinned_mat_override_metal_003_0[];
extern Gfx mario_000_displaylist_004_mesh[];
extern Gfx mario_000_displaylist_004_mesh_mat_override_metal_003_0[];
extern Gfx mario_002_switch_option_left_hand_open_mesh[];
extern Gfx mario_002_switch_option_left_hand_open_mesh_mat_override_metal_003_0[];
extern Gfx mario_004_switch_option_left_hand_peace_mesh[];
extern Gfx mario_004_switch_option_left_hand_peace_mesh_mat_override_metal_003_0[];
extern Gfx mario_005_switch_option_left_hand_cap_mesh[];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_mat_override_metal_003_0[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_mat_override_metal_003_0[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_009_mesh[];
extern Gfx mario_000_offset_009_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_009_skinned[];
extern Gfx mario_000_offset_009_skinned_mat_override_metal_003_0[];
extern Gfx mario_000_offset_010_mesh[];
extern Gfx mario_000_offset_010_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_010_skinned[];
extern Gfx mario_000_offset_010_skinned_mat_override_metal_003_0[];
extern Gfx mario_000_offset_011_mesh[];
extern Gfx mario_000_offset_011_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_012_mesh[];
extern Gfx mario_000_offset_012_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_012_skinned[];
extern Gfx mario_000_offset_012_skinned_mat_override_metal_003_0[];
extern Gfx mario_000_offset_013_mesh[];
extern Gfx mario_000_offset_013_mesh_mat_override_metal_003_0[];
extern Gfx mario_000_offset_013_skinned[];
extern Gfx mario_000_offset_013_skinned_mat_override_metal_003_0[];
extern Gfx mario_000_displaylist_005_mesh[];
extern Gfx mario_000_displaylist_005_mesh_mat_override_metal_003_0[];
extern Gfx mario_material_revert_render_settings[];

extern const GeoLayout super_ball_001_switch_opt1[];
extern const GeoLayout super_ball_001_switch_opt2[];
extern const GeoLayout super_ball_001_switch_opt3[];
extern const GeoLayout super_ball_geo[];
extern Vtx super_ball_000_offset_mesh_vtx_0[80];
extern Gfx super_ball_000_offset_mesh_tri_0[];

extern Gfx super_ball_000_offset_mesh[];
extern Gfx super_ball_000_offset_mesh_mat_override_metal_0[];
extern Gfx super_ball_material_revert_render_settings[];

extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7[];
extern const GeoLayout super_sonic_armature_002_switch_option_001[];
extern const GeoLayout super_sonic_right_hand_open_armature[];
extern const GeoLayout super_sonic_left_hand_open_armature[];
extern const GeoLayout super_sonic_left_hand_peace_armature[];
extern const GeoLayout super_sonic_left_hand_cap_armature[];
extern const GeoLayout super_sonic_left_hand_wing_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_armature_002_switch_option_001[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_right_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_left_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_left_hand_peace_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_left_hand_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_jump_super_sonic_left_hand_wing_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_armature_002_switch_option_001[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_right_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_left_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_left_hand_peace_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_left_hand_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2_jump_super_sonic_left_hand_wing_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_armature_002_switch_option_001[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_right_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_left_hand_open_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_left_hand_peace_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_left_hand_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3_jump_super_sonic_left_hand_wing_cap_armature[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[];
extern const GeoLayout super_sonic_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[];
extern const GeoLayout super_sonic_geo[];
extern Vtx super_sonic_000_offset_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_mesh_tri_0[];
extern Vtx super_sonic_000_offset_mesh_vtx_1[24];
extern Gfx super_sonic_000_offset_mesh_tri_1[];
extern Vtx super_sonic_000_offset_001_mesh_vtx_0[16];
extern Gfx super_sonic_000_offset_001_mesh_tri_0[];
extern Vtx super_sonic_000_offset_001_mesh_vtx_1[8];
extern Gfx super_sonic_000_offset_001_mesh_tri_1[];
extern Vtx super_sonic_000_offset_001_mesh_vtx_2[100];
extern Gfx super_sonic_000_offset_001_mesh_tri_2[];
extern Vtx super_sonic_000_offset_001_mesh_vtx_3[16];
extern Gfx super_sonic_000_offset_001_mesh_tri_3[];
extern Vtx super_sonic_000_offset_001_skinned_vtx_0[11];
extern Gfx super_sonic_000_offset_001_skinned_tri_0[];
extern Vtx super_sonic_000_offset_001_skinned_vtx_1[3];
extern Gfx super_sonic_000_offset_001_skinned_tri_1[];
extern Vtx super_sonic_000_displaylist_mesh_vtx_0[13];
extern Gfx super_sonic_000_displaylist_mesh_tri_0[];
extern Vtx super_sonic_000_displaylist_mesh_vtx_1[115];
extern Gfx super_sonic_000_displaylist_mesh_tri_1[];
extern Vtx super_sonic_000_displaylist_mesh_vtx_2[63];
extern Gfx super_sonic_000_displaylist_mesh_tri_2[];
extern Vtx super_sonic_000_displaylist_mesh_vtx_3[559];
extern Gfx super_sonic_000_displaylist_mesh_tri_3[];
extern Vtx super_sonic_002_switch_option_head__no_cap__mesh_vtx_0[103];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_tri_0[];
extern Vtx super_sonic_002_switch_option_head__no_cap__mesh_vtx_1[30];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_tri_1[];
extern Vtx super_sonic_002_switch_option_head__no_cap__mesh_vtx_2[12];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_tri_2[];
extern Vtx super_sonic_002_switch_option_head__no_cap__mesh_vtx_3[92];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_tri_3[];
extern Vtx super_sonic_000_displaylist_001_mesh_vtx_0[4];
extern Gfx super_sonic_000_displaylist_001_mesh_tri_0[];
extern Vtx super_sonic_000_displaylist_001_mesh_vtx_1[4];
extern Gfx super_sonic_000_displaylist_001_mesh_tri_1[];
extern Vtx super_sonic_000_displaylist_002_mesh_vtx_0[4];
extern Gfx super_sonic_000_displaylist_002_mesh_tri_0[];
extern Vtx super_sonic_000_displaylist_002_mesh_vtx_1[4];
extern Gfx super_sonic_000_displaylist_002_mesh_tri_1[];
extern Vtx super_sonic_000_offset_003_mesh_vtx_0[31];
extern Gfx super_sonic_000_offset_003_mesh_tri_0[];
extern Vtx super_sonic_000_offset_004_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_004_mesh_tri_0[];
extern Vtx super_sonic_000_offset_004_mesh_vtx_1[12];
extern Gfx super_sonic_000_offset_004_mesh_tri_1[];
extern Vtx super_sonic_000_offset_004_skinned_vtx_0[6];
extern Gfx super_sonic_000_offset_004_skinned_tri_0[];
extern Vtx super_sonic_000_displaylist_003_mesh_vtx_0[46];
extern Gfx super_sonic_000_displaylist_003_mesh_tri_0[];
extern Vtx super_sonic_002_switch_option_right_hand_open_mesh_vtx_0[58];
extern Gfx super_sonic_002_switch_option_right_hand_open_mesh_tri_0[];
extern Vtx super_sonic_000_offset_006_mesh_vtx_0[40];
extern Gfx super_sonic_000_offset_006_mesh_tri_0[];
extern Vtx super_sonic_000_offset_007_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_007_mesh_tri_0[];
extern Vtx super_sonic_000_offset_007_mesh_vtx_1[12];
extern Gfx super_sonic_000_offset_007_mesh_tri_1[];
extern Vtx super_sonic_000_offset_007_skinned_vtx_0[6];
extern Gfx super_sonic_000_offset_007_skinned_tri_0[];
extern Vtx super_sonic_000_displaylist_004_mesh_vtx_0[36];
extern Gfx super_sonic_000_displaylist_004_mesh_tri_0[];
extern Vtx super_sonic_002_switch_option_left_hand_open_mesh_vtx_0[57];
extern Gfx super_sonic_002_switch_option_left_hand_open_mesh_tri_0[];
extern Vtx super_sonic_004_switch_option_left_hand_peace_mesh_vtx_0[73];
extern Gfx super_sonic_004_switch_option_left_hand_peace_mesh_tri_0[];
extern Vtx super_sonic_005_switch_option_left_hand_cap_mesh_vtx_0[59];
extern Gfx super_sonic_005_switch_option_left_hand_cap_mesh_tri_0[];
extern Vtx super_sonic_005_switch_option_left_hand_cap_mesh_vtx_1[36];
extern Gfx super_sonic_005_switch_option_left_hand_cap_mesh_tri_1[];
extern Vtx super_sonic_006_switch_option_left_hand_wing_cap_mesh_vtx_0[59];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_mesh_tri_0[];
extern Vtx super_sonic_006_switch_option_left_hand_wing_cap_mesh_vtx_1[36];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_mesh_tri_1[];
extern Vtx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_vtx_0[8];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_tri_0[];
extern Vtx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_vtx_1[8];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_tri_1[];
extern Vtx super_sonic_000_offset_009_mesh_vtx_0[8];
extern Gfx super_sonic_000_offset_009_mesh_tri_0[];
extern Vtx super_sonic_000_offset_009_mesh_vtx_1[13];
extern Gfx super_sonic_000_offset_009_mesh_tri_1[];
extern Vtx super_sonic_000_offset_009_skinned_vtx_0[11];
extern Gfx super_sonic_000_offset_009_skinned_tri_0[];
extern Vtx super_sonic_000_offset_010_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_010_mesh_tri_0[];
extern Vtx super_sonic_000_offset_010_mesh_vtx_1[27];
extern Gfx super_sonic_000_offset_010_mesh_tri_1[];
extern Vtx super_sonic_000_offset_010_mesh_vtx_2[41];
extern Gfx super_sonic_000_offset_010_mesh_tri_2[];
extern Vtx super_sonic_000_offset_010_mesh_vtx_3[8];
extern Gfx super_sonic_000_offset_010_mesh_tri_3[];
extern Vtx super_sonic_000_offset_010_skinned_vtx_0[6];
extern Gfx super_sonic_000_offset_010_skinned_tri_0[];
extern Vtx super_sonic_000_offset_011_mesh_vtx_0[123];
extern Gfx super_sonic_000_offset_011_mesh_tri_0[];
extern Vtx super_sonic_000_offset_011_mesh_vtx_1[12];
extern Gfx super_sonic_000_offset_011_mesh_tri_1[];
extern Vtx super_sonic_000_offset_012_mesh_vtx_0[8];
extern Gfx super_sonic_000_offset_012_mesh_tri_0[];
extern Vtx super_sonic_000_offset_012_mesh_vtx_1[13];
extern Gfx super_sonic_000_offset_012_mesh_tri_1[];
extern Vtx super_sonic_000_offset_012_skinned_vtx_0[11];
extern Gfx super_sonic_000_offset_012_skinned_tri_0[];
extern Vtx super_sonic_000_offset_013_mesh_vtx_0[6];
extern Gfx super_sonic_000_offset_013_mesh_tri_0[];
extern Vtx super_sonic_000_offset_013_mesh_vtx_1[27];
extern Gfx super_sonic_000_offset_013_mesh_tri_1[];
extern Vtx super_sonic_000_offset_013_mesh_vtx_2[41];
extern Gfx super_sonic_000_offset_013_mesh_tri_2[];
extern Vtx super_sonic_000_offset_013_mesh_vtx_3[8];
extern Gfx super_sonic_000_offset_013_mesh_tri_3[];
extern Vtx super_sonic_000_offset_013_skinned_vtx_0[6];
extern Gfx super_sonic_000_offset_013_skinned_tri_0[];
extern Vtx super_sonic_000_displaylist_005_mesh_vtx_0[128];
extern Gfx super_sonic_000_displaylist_005_mesh_tri_0[];
extern Vtx super_sonic_000_displaylist_005_mesh_vtx_1[12];
extern Gfx super_sonic_000_displaylist_005_mesh_tri_1[];

extern Gfx super_sonic_000_offset_mesh[];
extern Gfx super_sonic_000_offset_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_001_mesh[];
extern Gfx super_sonic_000_offset_001_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_001_skinned[];
extern Gfx super_sonic_000_offset_001_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_mesh[];
extern Gfx super_sonic_000_displaylist_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_mesh_mat_override_face_0___eye_open_1[];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh[];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_002_switch_option_head__no_cap__mesh_mat_override_face_0___eye_open_1[];
extern Gfx super_sonic_000_displaylist_001_mesh[];
extern Gfx super_sonic_000_displaylist_001_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_002_mesh[];
extern Gfx super_sonic_000_displaylist_002_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_003_mesh[];
extern Gfx super_sonic_000_offset_003_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_004_mesh[];
extern Gfx super_sonic_000_offset_004_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_004_skinned[];
extern Gfx super_sonic_000_offset_004_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_003_mesh[];
extern Gfx super_sonic_000_displaylist_003_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_002_switch_option_right_hand_open_mesh[];
extern Gfx super_sonic_002_switch_option_right_hand_open_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_006_mesh[];
extern Gfx super_sonic_000_offset_006_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_007_mesh[];
extern Gfx super_sonic_000_offset_007_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_007_skinned[];
extern Gfx super_sonic_000_offset_007_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_004_mesh[];
extern Gfx super_sonic_000_displaylist_004_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_002_switch_option_left_hand_open_mesh[];
extern Gfx super_sonic_002_switch_option_left_hand_open_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_004_switch_option_left_hand_peace_mesh[];
extern Gfx super_sonic_004_switch_option_left_hand_peace_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_005_switch_option_left_hand_cap_mesh[];
extern Gfx super_sonic_005_switch_option_left_hand_cap_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_mesh[];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh[];
extern Gfx super_sonic_006_switch_option_left_hand_wing_cap_wings_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_009_mesh[];
extern Gfx super_sonic_000_offset_009_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_009_skinned[];
extern Gfx super_sonic_000_offset_009_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_010_mesh[];
extern Gfx super_sonic_000_offset_010_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_010_skinned[];
extern Gfx super_sonic_000_offset_010_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_011_mesh[];
extern Gfx super_sonic_000_offset_011_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_012_mesh[];
extern Gfx super_sonic_000_offset_012_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_012_skinned[];
extern Gfx super_sonic_000_offset_012_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_013_mesh[];
extern Gfx super_sonic_000_offset_013_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_000_offset_013_skinned[];
extern Gfx super_sonic_000_offset_013_skinned_mat_override_metal_003_0[];
extern Gfx super_sonic_000_displaylist_005_mesh[];
extern Gfx super_sonic_000_displaylist_005_mesh_mat_override_metal_003_0[];
extern Gfx super_sonic_material_revert_render_settings[];







#include "reticle/geo_header.h"





#include "emerald/geo_header.h"

#include "super_sonic/geo_header.h"

#include "emerald_circle/geo_header.h"

#include "sonic_ball/geo_header.h"

#include "super_ball/geo_header.h"





#include "mario/geo_header.h"

#endif
