extern const GeoLayout mario_cap_001_switch_opt1[];
extern const GeoLayout marios_cap_geo[];
extern Lights1 mario_cap_sonic_texture_v4_002_lights;
extern Lights1 mario_cap_sonic_buckle_v4_002_lights;
extern Lights1 mario_cap_sonic_shoe_v4_002_lights;
extern Lights1 mario_cap_sonic_white_v4_002_lights;
extern u8 mario_cap_sonic_new2_rgba16[];
extern Vtx mario_cap_000_displaylist_mesh_layer_1_vtx_0[134];
extern Gfx mario_cap_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx mario_cap_000_displaylist_mesh_layer_1_vtx_1[32];
extern Gfx mario_cap_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx mario_cap_000_displaylist_mesh_layer_1_vtx_2[92];
extern Gfx mario_cap_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx mario_cap_000_displaylist_mesh_layer_1_vtx_3[112];
extern Gfx mario_cap_000_displaylist_mesh_layer_1_tri_3[];
extern Gfx mat_mario_cap_sonic_texture_v4_002[];
extern Gfx mat_mario_cap_sonic_buckle_v4_002[];
extern Gfx mat_mario_cap_sonic_shoe_v4_002[];
extern Gfx mat_mario_cap_sonic_white_v4_002[];
extern Gfx mario_cap_000_displaylist_mesh_layer_1[];
extern Gfx mario_cap_material_revert_render_settings[];
