extern const GeoLayout emerald_000_switch_opt1[];
extern const GeoLayout emerald_000_switch_opt2[];
extern const GeoLayout emerald_000_switch_opt3[];
extern const GeoLayout emerald_000_switch_opt4[];
extern const GeoLayout emerald_000_switch_opt5[];
extern const GeoLayout emerald_000_switch_opt6[];
extern const GeoLayout emerald_geo[];
extern u8 emerald_emerald_green_rgba16[];
extern u8 emerald_emerald_yellow_rgba16[];
extern u8 emerald_emerald_blue_rgba16[];
extern u8 emerald_emerald_purple_rgba16[];
extern u8 emerald_emerald_gray_rgba16[];
extern u8 emerald_emerald_cyan_rgba16[];
extern u8 emerald_emerald_red_rgba16[];
extern Vtx emerald_000_displaylist_mesh_layer_1_vtx_0[50];
extern Gfx emerald_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_emerald_emeral_green_001[];
extern Gfx mat_revert_emerald_emeral_green_001[];
extern Gfx mat_emerald_emeral_yellow_001[];
extern Gfx mat_revert_emerald_emeral_yellow_001[];
extern Gfx mat_emerald_emeral_blue_001[];
extern Gfx mat_revert_emerald_emeral_blue_001[];
extern Gfx mat_emerald_emeral_purple_001[];
extern Gfx mat_revert_emerald_emeral_purple_001[];
extern Gfx mat_emerald_emeral_gray_001[];
extern Gfx mat_revert_emerald_emeral_gray_001[];
extern Gfx mat_emerald_emeral_cyan_001[];
extern Gfx mat_revert_emerald_emeral_cyan_001[];
extern Gfx mat_emerald_emeral_red_001[];
extern Gfx mat_revert_emerald_emeral_red_001[];
extern Gfx emerald_000_displaylist_mesh_layer_1[];
extern Gfx emerald_000_displaylist_mesh_layer_1_mat_override_emeral_yellow_001_0[];
extern Gfx emerald_000_displaylist_mesh_layer_1_mat_override_emeral_blue_001_1[];
extern Gfx emerald_000_displaylist_mesh_layer_1_mat_override_emeral_purple_001_2[];
extern Gfx emerald_000_displaylist_mesh_layer_1_mat_override_emeral_gray_001_3[];
extern Gfx emerald_000_displaylist_mesh_layer_1_mat_override_emeral_cyan_001_4[];
extern Gfx emerald_000_displaylist_mesh_layer_1_mat_override_emeral_red_001_5[];
extern Gfx emerald_material_revert_render_settings[];
